# Generated by Django 3.0.2 on 2020-04-03 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 15, 27, 48, 553857, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
