# Generated by Django 2.2.12 on 2020-04-03 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200403_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 16, 4, 4, 734371, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
