# Generated by Django 2.2.12 on 2020-04-04 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200403_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 7, 20, 3, 597545, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
