# Generated by Django 2.2.12 on 2020-04-08 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200408_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 12, 24, 57, 3831, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
