# Generated by Django 2.2.12 on 2020-04-08 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200408_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 13, 0, 37, 504189, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
