# Generated by Django 2.2.12 on 2020-04-17 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200408_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 6, 51, 33, 487579, tzinfo=utc), verbose_name='date/time published'),
        ),
    ]
